### ISSUE TITLE
direnv-hook-zsh.zsh gets out of date

### ISSUE THREAD

**Issue by antoineco** [zimfw/direnv#1]
### Prerequisites

- [X] I've checked the [existing issues](../issues?q=is%3Aissue) and I'm not duplicating a report.
- [X] I've checked the zimfw [Changelog](https://github.com/zimfw/zimfw/blob/master/CHANGELOG.md) and I'm not being affected by documented changes.
- [X] I've checked the zimfw [📢 Announcements](https://github.com/zimfw/zimfw/discussions/426?sort=new) and I'm not being affected by announced changes.

### Bug description

The current logic generates `direnv-hook-zsh.zsh` once, which does not take possible relocations of the `direnv` executable into account.

### Steps to reproduce

1. ```
   cd ${$(mktemp -d):A} && \
       ZDOTDIR=${PWD} HOME=${PWD} ZIM_HOME=${PWD}/.zim && \
       curl -fsSL https://raw.githubusercontent.com/zimfw/install/master/install.zsh | zsh && \
       exec zsh
   ```
1. Add `zmodule direnv` to zimrc
1. Install direnv
1. Open a new shell
1. Install direnv to a new location

My particular scenario is a `direnv` program installed via the Nix package manager using `nix profile install 'nixpkgs#direnv'` (or declarative equivalent on NixOS). Upon updating the program, its location changes inside the Nix store, and Zim's cached hook file no longer matches the current output of `direnv hook zsh`:

```diff
 _direnv_hook() {
   trap -- '' SIGINT
-  eval "$("/nix/store/bri4plkp5ykp2dvjs1bwzd92z7grp6h7-direnv-2.34.0/bin/direnv" export zsh)"
+  eval "$("/nix/store/3lv7pgadn5b587s69y23lpj90170q0n5-direnv-2.35.0/bin/direnv" export zsh)"
   trap - SIGINT
 }
```

### Current behavior

`direnv-hook-zsh.zsh` is never updated despite the `direnv` executable being a newer version installed at a different location on the filesystem.

### Expected behavior

`direnv-hook-zsh.zsh` is updated along with `direnv` when necessary, e.g. when the location of the current `direnv` no longer matches the one in the cached hook file).

### zimfw info

```shell
zimfw version:        1.15.1 (built at 2024-10-10 00:28:19 UTC, previous commit is 331f1c5)
LANG:                 en_US.UTF-8
OSTYPE:               linux-gnu
TERM:                 wezterm
TERM_PROGRAM:         WezTerm
TERM_PROGRAM_VERSION: 20240812-215703-30345b36
ZIM_HOME:             /home/acotten/.zim
ZSH_VERSION:          5.9
```

**Comment by antoineco** [comment]
I forgot to mention that the location of `direnv` in the PATH does not change. It is the target of the symlink which changes:

```console
% echo "${commands[direnv]}"
/etc/profiles/per-user/acotten/bin/direnv
```
```console
% ls -l "${commands[direnv]}"
lrwxrwxrwx 1 root root 68 Jan  1  1970 /etc/profiles/per-user/acotten/bin/direnv -> /nix/store/3lv7pgadn5b587s69y23lpj90170q0n5-direnv-2.35.0/bin/direnv
```

It seems like the 0 timestamps used across the Nix store are tripping the current `-nt` conditional expression:
https://github.com/zimfw/direnv/blob/8d395e563315b0193f375f2a83d27d93b249a5ea/init.zsh#L5

```console
% stat /nix/store/3lv7pgadn5b587s69y23lpj90170q0n5-direnv-2.35.0/bin/direnv
  File: /nix/store/3lv7pgadn5b587s69y23lpj90170q0n5-direnv-2.35.0/bin/direnv
  Size: 8284784         Blocks: 16184      IO Block: 4096   regular file
Device: 8,32    Inode: 2533042     Links: 1
Access: (0555/-r-xr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2024-11-16 11:05:11.000000000 +0000
Modify: 1970-01-01 00:00:01.000000000 +0000
Change: 2024-11-16 11:05:11.396581001 +0000
 Birth: 2024-11-16 11:05:11.077581001 +0000
```

This makes me wonder whether this issue can actually be addressed when using Nix.

**Comment by ericbn** [comment]
Hi @antoineco. Just saw this, I forgot to start watching this repo before.

Yeah, `-nt` looks at last modification time and it's unfortunate that nix does not update this timestamp. Looking for changes in the full path the symlink points to might be the next option. This would mean encoding the original full path in the cache script file name, which will potentially generate quite long names (like `direnv-hook-zsh-nix-store-3lv7pgadn5b587s69y23lpj90170q0n5-direnv-2.35.0-bin.zsh`). I want to avoid using any hashing command as that will add an extra command call, which defies the purpose of having a quick cache mechanism.

**Comment by antoineco** [comment]
Thanks for your answer!

Since the issue is pretty Nix-specific and I don't update `direnv` often I'll go ahead and close this issue. This hasn't been an issue for me so far, and if it becomes one I'll just clear the generated file :)

**Comment by ericbn** [comment]
Cool! Just out of curiosity, are you using zimfw installed via the nix package?

FYI to migrate to this, you would:
1. Install zimfw with nix
2. Update your .zshrc to do `source /path/to/zimfw.zsh init -q` with the nix-installed path instead of `source ${ZIM_HOME}/zimfw.zsh init -q`. E.g. using flox on an Intel Mac, it's `source ${HOME}/.flox/run/x86_64-darwin.default.run/zimfw.zsh init -q`.
3. Rebuild the init.zsh script with `source /path/to/zimfw.zsh build` again with the nix-installed path.
4. You can `rm ${ZIM_HOME}/zimfw.zsh` and remove the code in .zshrc that checks if the script exists there plus downloads it with curl or wget, since now the script will be managed by nix.

**Comment by antoineco** [comment]
I am not, I use Nix for package management and development shells mostly. My HOME is managed in a more traditional way, but I'll keep your instructions as a reference if I ever convert myself!
